# Generated by Django 5.0.6 on 2024-06-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('ikonka', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Bohater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('przydomek', models.CharField(max_length=100)),
                ('zdjecie', models.ImageField(upload_to='images')),
                ('Linia', models.ManyToManyField(to='www.linia')),
            ],
        ),
    ]
