# Generated by Django 5.0.6 on 2024-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('emblemat', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='bohater',
            name='Linia',
        ),
        migrations.AddField(
            model_name='bohater',
            name='linia',
            field=models.ManyToManyField(to='www.linia'),
        ),
    ]
