# Generated by Django 5.0.6 on 2024-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_rola_remove_bohater_linia_bohater_linia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bohater',
            name='rola',
            field=models.ManyToManyField(to='www.rola'),
        ),
    ]
