# Generated by Django 5.0.6 on 2024-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_remove_bohater_emblemat_remove_bohater_pozycja'),
    ]

    operations = [
        migrations.AddField(
            model_name='bohater',
            name='emblemat',
            field=models.CharField(default='Fill', max_length=100),
        ),
        migrations.AddField(
            model_name='bohater',
            name='pozycja',
            field=models.CharField(default='Fill', max_length=100),
        ),
    ]
