# Generated by Django 5.0.6 on 2024-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_bohater_emblemat_bohater_pozycja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bohater',
            name='emblemat',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
