# Generated by Django 5.0.6 on 2024-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_alter_bohater_emblemat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bohater',
            name='emblemat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bohater',
            name='pozycja',
            field=models.CharField(max_length=100),
        ),
    ]
